name: tf-lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
  workflow_dispatch:

jobs:
  tflint:
    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v2
      name: Checkout source code

    - uses: actions/setup-tflint@v2
      name: Setup TFLint
      with:
        tflint_version: v0.42.0

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact
